### ISSUE TITLE
Extend about:blank page

### ISSUE THREAD

**Issue by nick-kadutskyi** [fphilipe/PageExtender.app#21]
I was looking into a way to add some CSS to about:blank page to make it dark depending on my system theme color. Is there any way to do that with PageExtender?

**Comment by fphilipe** [comment]
Sounds like a great idea and easy to implement so I just did it quickly 😊 

Add this snippet to `blank.css`:

```css
:root {
  color-scheme: light dark;
  background-color: Canvas;
}
```

I'll make a release soon.
